services:
  web:
    # Mount source code for hot reload in development
    volumes:
      - ./src:/app/src
      - ./next.config.js:/app/next.config.js
      - ./.config:/app/.config
      - ./.babelrc.js:/app/.babelrc.js
      - ./.env:/app/.env:ro
