export default {
  DIALOG: 'DIALOG',
  GET_PROFILE: 'GET_PROFILE',
  GET_RAT: 'GET_RAT',
  GET_RESCUES: 'GET_RESCUES',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  RETRIEVE_PAPERWORK: 'RETRIEVE_PAPERWORK',
  SUBMIT_PAPERWORK: 'SUBMIT_PAPERWORK',
}
