export default {
  CREATE_RAT: 'CREATE_RAT',
  DIALOG: 'DIALOG',
  GET_PROFILE: 'GET_PROFILE',
  GET_RAT: 'GET_RAT',
  GET_RESCUES: 'GET_RESCUES',
  GET_USER: 'GET_USER',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  RETRIEVE_PAPERWORK: 'RETRIEVE_PAPERWORK',
  SUBMIT_PAPERWORK: 'SUBMIT_PAPERWORK',
  UPDATE_USER: 'UPDATE_USER',
}
