export {
  faAngleDown,
  faAngleUp,
  faArrowLeft,
  faArrowRight,
  faAsterisk,
  faBars,
  faBook,
  faCalendarAlt,
  faCaretDown,
  faCheck,
  faCheckCircle,
  faCircle,
  faClipboardCheck,
  faClipboardList,
  faClock,
  faCodeBranch,
  faEllipsisH,
  faExclamationTriangle,
  faExclamationCircle,
  faEye,
  faEyeSlash,
  faFileUpload,
  faFirstAid,
  faFolder,
  faFolderOpen,
  faHandsHelping,
  faIdCardAlt,
  faMouse,
  faPen,
  faPlus,
  faRocket,
  faShieldAlt,
  faShoePrints,
  faSignature,
  faSpaceShuttle,
  faSpinner,
  faSync,
  faTimes,
  faTimesCircle,
  faTrash,
  faTv,
  faSearch,
  faUser,
  faUserSecret,
  faUpload,
} from '@fortawesome/free-solid-svg-icons'

export {
  faRedditAlien,
  faTwitch,
  faGithub,
  faMastodon,
  faPlaystation,
  faXbox,
} from '@fortawesome/free-brands-svg-icons'
