export {
  faAngleDown,
  faAngleUp,
  faArrowLeft,
  faArrowRight,
  faAsterisk,
  faBars,
  faBell,
  faBellSlash,
  faBook,
  faCalendarAlt,
  faCaretDown,
  faChevronDown,
  faChevronRight,
  faChevronUp,
  faCheck,
  faCheckCircle,
  faCircle,
  faCircleQuestion,
  faClipboardCheck,
  faClipboardList,
  faClock,
  faCodeBranch,
  faEllipsisH,
  faExclamationTriangle,
  faExclamationCircle,
  faEye,
  faEyeSlash,
  faFileUpload,
  faFirstAid,
  faFolder,
  faFolderOpen,
  faHandsHelping,
  faIdCard,
  faIdCardAlt,
  faMobileScreen,
  faMouse,
  faPen,
  faPlus,
  faRocket,
  faShieldAlt,
  faShoePrints,
  faSignature,
  faSpaceShuttle,
  faSpinner,
  faStar,
  faSync,
  faTimes,
  faTimesCircle,
  faTrash,
  faTv,
  faSearch,
  faUser,
  faUserSecret,
  faUpload,
  faBagShopping,
  faBoxArchive,
  faKey,
  faLock,
  faGasPump,
  faCircleXmark,
  faChalkboardUser,
  faCode,
  faDesktop,
  faDownload,
  faGavel,
  faGears,
  faGraduationCap,
  faHeadset,
  faSnowflake,
  faUpRightFromSquare,
} from '@fortawesome/free-solid-svg-icons'

export {
  faRedditAlien,
  faTwitch,
  faGithub,
  faMastodon,
  faPlaystation,
  faXbox,
} from '@fortawesome/free-brands-svg-icons'

export {
  faStar as farStar,
} from '@fortawesome/free-regular-svg-icons'
