export {
  faAngleDown,
  faAngleUp,
  faArrowLeft,
  faArrowRight,
  faAsterisk,
  faBars,
  faCaretDown,
  faBook,
  faCheck,
  faCheckCircle,
  faCircle,
  faClipboardCheck,
  faClipboardList,
  faClock,
  faCodeBranch,
  faEllipsisH,
  faExclamationTriangle,
  faExclamationCircle,
  faEye,
  faEyeSlash,
  faFirstAid,
  faFolder,
  faFolderOpen,
  faHandsHelping,
  faIdCardAlt,
  faInfoCircle,
  faMoneyBill,
  faMouse,
  faPen,
  faPlus,
  faRocket,
  faShieldAlt,
  faShoePrints,
  faShoppingCart,
  faSignature,
  faSpaceShuttle,
  faSpinner,
  faSync,
  faTimes,
  faTimesCircle,
  faTrash,
  faTruck,
  faUndo,
  faUser,
  faUserSecret,
  faUpload,
  faSearchPlus,
  faSearchMinus,
  faRedo,
} from '@fortawesome/free-solid-svg-icons'

export {
  faTwitter,
  faRedditAlien,
  faTwitch,
  faGithub,
} from '@fortawesome/free-brands-svg-icons'
