name: Test

on:
  pull_request:
    branches: [ develop, release ]

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.owner.login == github.repository_owner }}
    name: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint JS
        run: bun run lint:js -- --max-warnings 0

      - name: Lint CSS
        run: bun run lint:css -- --max-warnings 0

  build:
    runs-on: ubuntu-latest
    name: Docker Build Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
